"use strict";
let leagueData=null;let pairRanking=[];
document.addEventListener("DOMContentLoaded",()=>{configureMenu();loadLeagueData();});
function configureMenu(){const b=document.getElementById("menuButton"),m=document.getElementById("mainMenu");b.addEventListener("click",()=>{const o=m.classList.toggle("open");b.setAttribute("aria-expanded",String(o));document.body.classList.toggle("menu-open",o);});m.querySelectorAll("a").forEach(a=>a.addEventListener("click",()=>{m.classList.remove("open");b.setAttribute("aria-expanded","false");document.body.classList.remove("menu-open");}));}
async function loadLeagueData(){try{const r=await fetch("data.json",{cache:"no-store"});if(!r.ok)throw new Error("No se pudo cargar data.json");leagueData=await r.json();validateData();pairRanking=calculatePairRanking();renderFilters();renderAll();}catch(e){console.error(e);document.body.innerHTML=`<main style="padding:40px;font-family:Arial"><h1>Error cargando la liga</h1><p>${escapeHtml(e.message)}</p><pre>python -m http.server 8000</pre></main>`;}}
function validateData(){if(!Array.isArray(leagueData.players)||!Array.isArray(leagueData.matches))throw new Error("data.json debe contener players y matches");leagueData.matches.forEach(m=>{if(!Array.isArray(m.teamA)||m.teamA.length!==2||!Array.isArray(m.teamB)||m.teamB.length!==2)throw new Error("Cada pareja debe tener dos jugadores");if(!["A","B"].includes(m.winner))throw new Error("winner debe ser A o B");});}
function renderAll(){renderHeader();renderDashboard();renderMatches();renderLatestMatch();renderPodium();renderRanking();renderPairCards();renderPlayers();renderCharts();}
function player(id){return leagueData.players.find(p=>p.id===id)}function playerName(id){return player(id)?.name||id}function playerPhoto(id){return player(id)?.photo||"images/placeholder.svg"}function normalisePair(ids){return ids.slice().sort()}function pairKey(ids){return normalisePair(ids).join("__")}function pairName(ids){return normalisePair(ids).map(playerName).join(" / ")}
function pairAvatars(ids,large=false){return `<div class="pair-avatars ${large?'pair-avatars-large':''}">${normalisePair(ids).map(id=>`<img class="pair-avatar" src="${escapeHtml(playerPhoto(id))}" alt="Foto de ${escapeHtml(playerName(id))}" onerror="this.src='images/placeholder.svg'">`).join("")}</div>`;}
function matchScore(m){const s={setsA:0,setsB:0,gamesA:0,gamesB:0};m.sets.forEach(x=>{s.gamesA+=Number(x[0]);s.gamesB+=Number(x[1]);x[0]>x[1]?s.setsA++:s.setsB++;});return s}function formatSets(sets){return sets.map(x=>`${x[0]}-${x[1]}`).join(" · ")}function formatDate(d){return new Intl.DateTimeFormat("es-ES",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(d+"T12:00:00"))}
function calculatePairRanking(){const pairs={};leagueData.matches.forEach(m=>{const s=matchScore(m);updatePair(pairs,m.teamA,m.winner==="A",s.setsA,s.setsB,s.gamesA,s.gamesB);updatePair(pairs,m.teamB,m.winner==="B",s.setsB,s.setsA,s.gamesB,s.gamesA);});return Object.values(pairs).sort(comparePairs)}
function updatePair(pairs,ids,won,sf,sa,gf,ga){const sorted=normalisePair(ids),key=pairKey(sorted);if(!pairs[key])pairs[key]={key,playerIds:sorted,name:pairName(sorted),played:0,wins:0,losses:0,points:0,setsFor:0,setsAgainst:0,gamesFor:0,gamesAgainst:0};const p=pairs[key];p.played++;p.setsFor+=sf;p.setsAgainst+=sa;p.gamesFor+=gf;p.gamesAgainst+=ga;if(won){p.wins++;p.points+=Number(leagueData.settings.pointsForWin)}else{p.losses++;p.points+=Number(leagueData.settings.pointsForLoss)}}
function comparePairs(a,b){return b.points-a.points||b.wins-a.wins||(b.setsFor-b.setsAgainst)-(a.setsFor-a.setsAgainst)||(b.gamesFor-b.gamesAgainst)-(a.gamesFor-a.gamesAgainst)||a.name.localeCompare(b.name,"es")}function winRate(p){return !p||!p.played?0:Math.round(p.wins/p.played*100)}function totalSets(){return leagueData.matches.reduce((n,m)=>n+m.sets.length,0)}
function renderHeader(){const l=pairRanking[0];document.getElementById("seasonTitle").textContent=leagueData.season||"Resumen";if(!l)return;document.getElementById("heroLeaderAvatars").outerHTML=pairAvatars(l.playerIds,true).replace('class="pair-avatars pair-avatars-large"','id="heroLeaderAvatars" class="pair-avatars pair-avatars-large"');document.getElementById("heroLeader").textContent=l.name;document.getElementById("heroLeaderInfo").textContent=`${l.points} puntos · ${l.wins} victorias · ${winRate(l)}% win rate`;}
function renderDashboard(){const l=pairRanking[0];const data=[["Partidos",leagueData.matches.length,"Encuentros registrados"],["Parejas",pairRanking.length,"Combinaciones diferentes"],["Jugadores",leagueData.players.length,"Información complementaria"],["Sets",totalSets(),"Sets disputados"],["Pareja líder",l?.name||"-",l?`${l.points} puntos`:"Sin datos"],["Puntos victoria",leagueData.settings.pointsForWin,"Por ganar"],["Puntos derrota",leagueData.settings.pointsForLoss,"Por perder"],["Tercer tiempo","Champions","Nuestro verdadero nivel"]];document.getElementById("kpiGrid").innerHTML=data.map(x=>`<article class="kpi-card"><span class="kpi-label">${escapeHtml(x[0])}</span><strong class="kpi-value">${escapeHtml(x[1])}</strong><span class="kpi-description">${escapeHtml(x[2])}</span></article>`).join("")}
function renderFilters(){const d=document.getElementById("dateFilter"),p=document.getElementById("playerFilter"),t=document.getElementById("textFilter");const dates=[...new Set(leagueData.matches.map(m=>m.date))].sort().reverse();d.innerHTML='<option value="all">Todas</option>'+dates.map(x=>`<option value="${x}">${formatDate(x)}</option>`).join("");p.innerHTML='<option value="all">Todos</option>'+leagueData.players.map(x=>`<option value="${escapeHtml(x.id)}">${escapeHtml(x.name)}</option>`).join("");[d,p].forEach(x=>x.addEventListener("change",renderMatches));t.addEventListener("input",renderMatches);document.getElementById("clearFilters").addEventListener("click",()=>{d.value="all";p.value="all";t.value="";renderMatches()})}
function renderMatches(){const d=document.getElementById("dateFilter").value,p=document.getElementById("playerFilter").value,t=document.getElementById("textFilter").value.trim().toLowerCase();const ms=leagueData.matches.filter(m=>(d==="all"||m.date===d)&&(p==="all"||m.teamA.includes(p)||m.teamB.includes(p))&&(!t||[m.title,m.court,pairName(m.teamA),pairName(m.teamB)].join(" ").toLowerCase().includes(t))).sort((a,b)=>b.date.localeCompare(a.date));document.getElementById("matchesContainer").innerHTML=ms.length?ms.map(matchCard).join(""):'<div class="empty-state">No hay partidos con esos filtros.</div>'}
function matchCard(m){const s=matchScore(m);return `<article class="match-card"><div class="match-header"><div><span class="match-date">${formatDate(m.date)}</span><h3 class="match-title">${escapeHtml(m.title)}</h3></div><span class="match-court">${escapeHtml(m.court)}</span></div><div class="match-teams"><div class="match-team ${m.winner==='A'?'winner':''}"><span class="match-team-name">${escapeHtml(pairName(m.teamA))}</span><span class="match-team-sets">${s.setsA}</span></div><div class="match-team ${m.winner==='B'?'winner':''}"><span class="match-team-name">${escapeHtml(pairName(m.teamB))}</span><span class="match-team-sets">${s.setsB}</span></div></div><div class="match-score">Sets: ${escapeHtml(formatSets(m.sets))}</div></article>`}
function renderLatestMatch(){if(!leagueData.matches.length)return;const m=leagueData.matches.slice().sort((a,b)=>b.date.localeCompare(a.date))[0],s=matchScore(m);document.getElementById("lastMatchPanel").innerHTML=`<h3 class="latest-title">${escapeHtml(m.title)}</h3><div class="latest-team"><span>${escapeHtml(pairName(m.teamA))}</span><strong>${s.setsA}</strong></div><div class="latest-team"><span>${escapeHtml(pairName(m.teamB))}</span><strong>${s.setsB}</strong></div><p class="latest-score">${formatDate(m.date)}<br>${escapeHtml(formatSets(m.sets))}</p>`}
function renderPodium(){const medals=["🥇","🥈","🥉"];document.getElementById("podium").innerHTML=pairRanking.slice(0,3).map((p,i)=>`<article class="podium-card position-${i+1}"><div class="podium-medal">${medals[i]}</div>${pairAvatars(p.playerIds).replace('class="pair-avatars"','class="pair-avatars center"')}<h3 class="podium-pair">${escapeHtml(p.name)}</h3><div class="podium-points">${p.points} pts</div><p class="podium-detail">${p.wins} victorias · ${winRate(p)}% win rate</p></article>`).join("")}
function renderRanking(){document.getElementById("rankingBody").innerHTML=pairRanking.map((p,i)=>`<tr><td>${i<3?["🥇 1","🥈 2","🥉 3"][i]:i+1}</td><td><div class="ranking-pair-cell">${pairAvatars(p.playerIds)}<strong>${escapeHtml(p.name)}</strong></div></td><td class="ranking-points">${p.points}</td><td>${p.played}</td><td>${p.wins}</td><td>${p.losses}</td><td>${p.setsFor}-${p.setsAgainst}</td><td>${p.gamesFor}-${p.gamesAgainst}</td><td>${winRate(p)}%</td></tr>`).join("")}
function renderPairCards(){document.getElementById("pairsContainer").innerHTML=pairRanking.map((p,i)=>`<article class="pair-card ${i===0?'leader':''}"><div class="pair-card-top"><div class="pair-title-wrap">${pairAvatars(p.playerIds)}<h3>${escapeHtml(p.name)}</h3></div><span class="pair-rank">${i+1}</span></div><div class="pair-stats">${stat(p.points,"Pts")}${stat(p.played,"PJ")}${stat(p.wins,"V")}${stat(winRate(p)+"%","Win")}</div></article>`).join("")}function stat(v,l){return `<div class="pair-stat"><strong>${escapeHtml(v)}</strong><span>${l}</span></div>`}
function renderPlayers(){document.getElementById("playersContainer").innerHTML=leagueData.players.map(p=>`<article class="player-card"><img class="player-photo" src="${escapeHtml(p.photo)}" alt="Foto de ${escapeHtml(p.name)}" loading="lazy" onerror="this.src='images/placeholder.svg'"><div class="player-details"><h3>${escapeHtml(p.name)}</h3><div class="player-role">${escapeHtml(p.role)}</div><p class="player-description">${escapeHtml(p.description)}</p></div></article>`).join("")}
function renderCharts(){const top=pairRanking.slice(0,8),max=top[0]?.points||0;document.getElementById("pointsChart").innerHTML=top.map(p=>bar(p.name,p.points+" pts",max?Math.round(p.points/max*100):0)).join("");document.getElementById("winRateChart").innerHTML=pairRanking.slice().sort((a,b)=>winRate(b)-winRate(a)||b.played-a.played).slice(0,8).map(p=>bar(p.name,winRate(p)+"%",winRate(p))).join("")}
function bar(l,v,w){return `<div><div class="bar-header"><span>${escapeHtml(l)}</span><span>${escapeHtml(v)}</span></div><div class="bar-track"><div class="bar-fill" style="width:${Math.max(0,Math.min(100,w))}%"></div></div></div>`}function escapeHtml(v){return String(v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;")}
